import { defineField, defineType } from "sanity";
import {
  authorField,
  bodyField,
  coverImageField,
  excerptField,
  locationField,
  slugField,
  titleField,
} from "./shared";

export const stayReview = defineType({
  name: "stayReview",
  title: "Stay",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "classification", title: "Classification" },
    { name: "details", title: "Useful info" },
    { name: "scoring", title: "Scoring" },
    { name: "advanced", title: "Advanced" },
  ],
  fields: [
    defineField({ ...titleField, group: "content" }),
    defineField({ ...slugField, group: "content" }),
    defineField({
      ...excerptField,
      group: "content",
      description: "Also used as the default meta description and social sharing text.",
    }),
    defineField({
      ...coverImageField,
      group: "content",
      title: "Main image",
      description: "One image for the review hero, cards, homepage feature, and social sharing preview.",
    }),
    defineField({ ...bodyField, group: "content" }),
    defineField({
      name: "image",
      title: "Legacy image fallback",
      type: "image",
      hidden: true,
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alt text", type: "string" }),
        defineField({ name: "caption", title: "Caption", type: "string" }),
        defineField({ name: "credit", title: "Image credit", type: "string" }),
      ],
      group: "advanced",
      description: "Old image field kept as a fallback for older content. Use Main image instead.",
    }),
    defineField({ ...locationField, group: "classification", description: "Display location, e.g. Perhentian Kecil, Malaysia." }),
    defineField({
      name: "place",
      title: "Linked place / destination",
      type: "reference",
      to: [{ type: "destination" }],
      group: "classification",
      description: "Optional, but useful for grouping stays under a destination page.",
    }),
    defineField({
      name: "city",
      title: "City / area",
      type: "string",
      group: "classification",
      description: "Example: Shanghai, Wuzhen, Perhentian Kecil.",
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
      group: "classification",
      description: "Example: China, Malaysia.",
    }),
    defineField({
      name: "stayTypes",
      title: "Type of stay",
      type: "array",
      group: "classification",
      of: [
        {
          type: "string",
          options: {
            list: [
              { title: "5-star", value: "5-star" },
              { title: "Luxury", value: "luxury" },
              { title: "Midrange", value: "midrange" },
              { title: "Budget", value: "budget" },
              { title: "Resort", value: "resort" },
              { title: "Boutique hotel", value: "boutique-hotel" },
              { title: "City hotel", value: "city-hotel" },
              { title: "Beach hotel", value: "beach-hotel" },
              { title: "Airbnb / rental", value: "airbnb-rental" },
              { title: "Family-friendly", value: "family-friendly" },
              { title: "Romantic", value: "romantic" },
            ],
          },
        },
      ],
      options: { layout: "tags" },
      description: "Choose all that apply. These can power filters later.",
    }),
    defineField({
      name: "websiteUrl",
      title: "Website link",
      type: "url",
      group: "details",
    }),
    defineField({ name: "price", title: "Price", type: "string", group: "details", description: "Example: $$$$ - from MYR 1,650 / night" }),
    defineField({ name: "goodFor", title: "Good for", type: "string", group: "details", description: "Short useful-info line." }),
    defineField({ name: "bestTime", title: "Best time", type: "string", group: "details", description: "Example: April - early October" }),
    defineField({ name: "avoid", title: "Avoid", type: "string", group: "details" }),
    defineField({ name: "nights", title: "Nights", type: "number", group: "details", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "verdict", title: "Verdict", type: "string", group: "details" }),
    defineField({ name: "bestFor", title: "Best for", type: "array", group: "details", of: [{ type: "string" }] }),
    defineField({
      name: "loved",
      title: "Loved",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "lessSo",
      title: "Less so",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "disclosure",
      title: "Disclosure",
      type: "text",
      rows: 3,
      group: "details",
    }),
    defineField({
      name: "heroCaption",
      title: "Hero image caption",
      type: "string",
      group: "details",
      description: "Optional. If blank, the Main image caption is used.",
    }),
    defineField({
      name: "stayScores",
      title: "Stay scoring",
      type: "object",
      group: "scoring",
      description: "The public star rating is averaged from these five scores.",
      fields: [
        defineField({
          name: "walletCry",
          title: "Did My Wallet Cry?",
          description: "value for money",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
        defineField({
          name: "breakfastTest",
          title: "The Breakfast Test",
          description: "because a bad breakfast ruins everything",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
        defineField({
          name: "gramWorthy",
          title: "Gram-Worthy?",
          description: "is it as photogenic as the website promised",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
        defineField({
          name: "welcomeFactor",
          title: "The Welcome Factor",
          description: "did the service live up to expectations?",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
        defineField({
          name: "worthDaysOff",
          title: "Worth My Precious Days Off",
          description: "the ultimate infrequent traveller question",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
      ],
    }),
    defineField({ name: "rating", title: "Legacy rating override", type: "number", group: "advanced", validation: (Rule) => Rule.min(0).max(5), description: "Only used if Stay scoring is empty." }),
    defineField({ name: "readingTime", title: "Reading time", type: "string", group: "advanced", description: "Optional legacy display field. Not needed for the stay review hero." }),
    defineField({ ...authorField, group: "advanced" }),
    defineField({ name: "publishedDate", title: "Published date", type: "date", group: "advanced" }),
    defineField({
      name: "metadata",
      title: "SEO overrides",
      type: "pageMetadata",
      group: "advanced",
      description: "Optional. If blank, title, excerpt, and Main image are used automatically.",
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "location", media: "coverImage" },
  },
});
