import { defineField, defineType } from "sanity";
import {
  authorField,
  bodyField,
  coverImageField,
  excerptField,
  imageField,
  locationField,
  ratingField,
  readingTimeField,
  seoFields,
  slugField,
  titleField,
} from "./shared";

export const stayReview = defineType({
  name: "stayReview",
  title: "Stay",
  type: "document",
  fields: [
    titleField,
    slugField,
    excerptField,
    bodyField,
    imageField,
    coverImageField,
    locationField,
    readingTimeField,
    ratingField,
    defineField({
      name: "websiteUrl",
      title: "Website link",
      type: "url",
    }),
    defineField({
      name: "stayScores",
      title: "Stay scoring",
      type: "object",
      fields: [
        defineField({
          name: "walletCry",
          title: "Did My Wallet Cry?",
          description: "value for money",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
        defineField({
          name: "breakfastTest",
          title: "The Breakfast Test",
          description: "because a bad breakfast ruins everything",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
        defineField({
          name: "gramWorthy",
          title: "Gram-Worthy?",
          description: "is it as photogenic as the website promised",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
        defineField({
          name: "welcomeFactor",
          title: "The Welcome Factor",
          description: "did the service live up to expectations?",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
        defineField({
          name: "worthDaysOff",
          title: "Worth My Precious Days Off",
          description: "the ultimate infrequent traveller question",
          type: "number",
          validation: (Rule) => Rule.min(0).max(5).warning("Use a score from 0 to 5."),
        }),
      ],
    }),
    defineField({ name: "nights", title: "Nights", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "verdict", title: "Verdict", type: "string" }),
    defineField({ name: "bestFor", title: "Best for", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "avoid", title: "Avoid", type: "string" }),
    authorField,
    defineField({ name: "publishedDate", title: "Published date", type: "date" }),
    ...seoFields,
  ],
  preview: {
    select: { title: "title", subtitle: "location", media: "image" },
  },
});
